### ISSUE TITLE
The demo is not worked

### ISSUE THREAD

**Issue by zetay** [Good-Coders/node-image-resize#2]
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by devshekhawat** [comment]
I found this link related to this issue 
[https://stackoverflow.com/questions/16222116/error-spawn-enoent-while-using-gm-in-node](https://stackoverflow.com/questions/16222116/error-spawn-enoent-while-using-gm-in-node)

**Comment by knoxcard** [comment]
This worked for me, lol

https://www.npmjs.com/package/imagemagick
sudo apt-get install imagemagick

**even better, use Yarn, get away from NPM...**
yarn add imagemagick


im.resize({
  srcPath: 'kittens.jpg',
  dstPath: 'kittens-small.jpg',
  width:   256
}, function(err, stdout, stderr){
  if (err) throw err;
  console.log('resized kittens.jpg to fit within 256x256px');
})
